name: tablark
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.3 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets: 
    - lib/assets/graphics/
    - lib/assets/graphics/jpg/
    - lib/assets/graphics/png/
    - lib/assets/graphics/svg/

  fonts:
  - family: Quicksand
    fonts:
      - asset: lib/assets/fonts/Quicksand-Light.ttf
        weight: 300
      - asset: lib/assets/fonts/Quicksand-Regular.ttf
        weight: 400
      - asset: lib/assets/fonts/Quicksand-Medium.ttf
        weight: 500
      - asset: lib/assets/fonts/Quicksand-SemiBold.ttf
        weight: 600
      - asset: lib/assets/fonts/Quicksand-Bold.ttf
        weight: 700

